/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 brain.gltf 
Author: Dean Lavery (https://sketchfab.com/dean.lavery)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-project-24ec03412dd8432bb0d3e750a72608e0
Title: Brain Project
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brain.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brain_Part_01_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
      <mesh geometry={nodes.Brain_Part_02_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
      <mesh geometry={nodes.Brain_Part_03_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
      <mesh geometry={nodes.Brain_Part_04_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
      <mesh geometry={nodes.Brain_Part_05_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
      <mesh geometry={nodes.Brain_Part_06_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
    </group>
  )
}

useGLTF.preload('/brain.gltf')
